SELECT * FROM TAB;

DESC EMPLOYEES;

SELECT * FROM EMPLOYEES;

-- 직원번호가 100인 사람을 출력
SELECT * 
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 100;
 
 -- KING 이라는 직원을 출력
SELECT * 
FROM EMPLOYEES 
WHERE LAST_NAME = 'King';

-- 월급 내림차순으로 직원정보를 출력
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
 FROM EMPLOYEES
 ORDER BY salary DESC; --107
 
 -- 월급 내림차순으로 월급이 5000이상인 직원정보를 출력
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
 FROM EMPLOYEES
 WHERE SALARY >= 5000
 ORDER BY salary DESC; --58
 
 -- 전화번호에 100이 포함된 직원
 SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER
 FROM EMPLOYEES
 WHERE PHONE_NUMBER like '%010%'
 ORDER BY phone_number ASC;
 
 -- 50번 부서의 직원을 출력
 SELECT EMPLOYEE_ID                  "사 번", -- 띄어쓰기시 에러/쌍따움표안에 있어야 같이나옴ㅇㅇ
        FIRST_NAME||' '||LAST_NAME   이름,
        DEPARTMENT_ID                부서번호
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID LIKE 50
  --ORDER BY FIRST_NAME||' '||LAST_NAME ASC;
  ORDER BY FIRST_NAME ASC, LAST_NAME ASC;
  

  -- 부서가 없는 직원을 출력
  SELECT EMPLOYEE_ID
        , FIRST_NAME||' '||LAST_NAME   ENAME
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID IS NULL;      -- = NULL : 작동안함, IS NULL : 작동함, IS NOT NULL : 