SELECT * FROM TAB;

DESC EMPLOYEES;

SELECT * FROM EMPLOYEES;

-- 직원번호가 100인 사람을 출력
SELECT * 
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 100;
 
 -- KING 이라는 직원을 출력
SELECT * 
FROM EMPLOYEES 
WHERE LAST_NAME = 'King';

-- 월급 내림차순으로 직원정보를 출력
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
 FROM EMPLOYEES
 ORDER BY salary DESC; --107
 
 -- 월급 내림차순으로 월급이 5000이상인 직원정보를 출력
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
 FROM EMPLOYEES
 WHERE SALARY >= 5000
 ORDER BY salary DESC; --58
 
 -- 전화번호에 100이 포함된 직원
 SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
 FROM EMPLOYEES
 WHERE PHONE_NUMBER >= 100
 ORDER BY phone_number DESC;
 
 -- 50번 부서의 직원을 출력
 
 -- 부서가 없는 직원을 출력