SELECT * FROM TAB;


---------------------------------------------
--SUBQUERY : SQL 문 안에 SQL 문을 넣어서 실행하는 방법
--           반드시 () 안에 있어야 한다
--           ()안에는 ORDER BY 사용불가
--           WHERE 조건에 맞도록 작성한다
--           쿼리를 실행하는 순서가 필요할때
---------------------------------------------

-- IT 부서의 직원정보 출력
--1. IT 부서의 부서번호를 찾는다
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT'
;

--2.60번 부서의 직원정보를 출력
SELECT EMPLOYEE_ID,
       FIRST_NAME ||' '|| LAST_NAME,
       DEPARTMENT_ID
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID = 60
;

-- 1+2)
SELECT EMPLOYEE_ID,
       FIRST_NAME ||' '|| LAST_NAME,
       DEPARTMENT_ID
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID =(
       SELECT DEPARTMENT_ID
       FROM DEPARTMENTS
       WHERE DEPARTMENT_NAME = 'IT')
;

SELECT EMPLOYEE_ID,
       FIRST_NAME ||' '|| LAST_NAME,
       DEPARTMENT_ID
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID IN (
       SELECT DEPARTMENT_ID
       FROM DEPARTMENTS
       WHERE DEPARTMENT_NAME IN ('IT', 'SALES'))
       ;
       
-- 평균월급보다 많은 월급을 받는 사람의 명단
-- 평균월급 : 6461.831775700934579439252336448598130841
SELECT  AVG(SALARY) --반올림은 최종 출력때만
FROM    EMPLOYEES
;

-- 월급이 6461.831775700934579439252336448598130841 보다 많은 직원
SELECT EMPLOYEE_ID
       FIRST_NAME,
       LAST_NAME,
       SALARY
FROM   EMPLOYEES
WHERE  SALARY >=6461.831775700934579439252336448598130841
;

-- 1+2
SELECT  EMPLOYEE_ID
        FIRST_NAME,
        LAST_NAME,
        SALARY
FROM    EMPLOYEES
WHERE   SALARY >=(
        SELECT  AVG(SALARY)
        FROM    EMPLOYEES)
;

-- 60번 부서의 평균월급보다 많은 월급을 받는사람의 명단

SELECT EMPLOYEE_ID,
       FIRST_NAME ||' '|| LAST_NAME,
       DEPARTMENT_ID,
       SALARY
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID = 60
;

SELECT  AVG(SALARY)
FROM    EMPLOYEES
WHERE   DEPARTMENT_ID = 60
;


SELECT EMPLOYEE_ID,
       FIRST_NAME ||' '|| LAST_NAME,
       SALARY
FROM   EMPLOYEES
WHERE  SALARY >= 5760
ORDER BY SALARY
;

-- SALES 부서의 평균월급보다 많은 월급을 받는 사람의 명단
SELECT  AVG(SALARY)
FROM    EMPLOYEES
WHERE   DEPARTMENT_ID = 60
;

SELECT  AVG(SALARY)
FROM    EMPLOYEES
WHERE   DEPARTMENT_ID = (
        SELECT  DEPARTMENT_ID
        FROM    DEPARTMENTS
        WHERE   DEPARTMENT_NAME = 'IT'
)
;

SELECT EMPLOYEE_ID,
       FIRST_NAME ||' '|| LAST_NAME,
       SALARY
FROM   EMPLOYEES
WHERE  SALARY >= (
SELECT  AVG(SALARY)
FROM    EMPLOYEES
WHERE   DEPARTMENT_ID=(
        SELECT  DEPARTMENT_ID
        FROM    DEPARTMENTS
        WHERE   DEPARTMENT_NAME = 'IT')
)
;

-- 50번 부서의 최고 월급자의 이름을 출력
SELECT MAX(SALARY)
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID = 50
;

SELECT EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       SALARY
FROM   EMPLOYEES
WHERE  SALARY = 8200
;

SELECT EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       SALARY,
       DEPARTMENT_ID
FROM   EMPLOYEES
WHERE  SALARY = (
SELECT MAX(SALARY)
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID = 50
)
AND    DEPARTMENT_ID = 50
;

-- SALES 부서의 평균월급보다 많은 월급을 받는사람의 명단
SELECT DEPARTMENT_ID
FROM   DEPARTMENTS
WHERE  UPPER(DEPARTMENT_NAME) = 'SALES'
;

SELECT AVG(SALARY)
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID = 80
;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM  EMPLOYEES
WHERE SALARY >= 8955.882352941176470588235294117647058824
;

SELECT  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM    EMPLOYEES
WHERE   SALARY >= (
        SELECT AVG(SALARY)
        FROM   EMPLOYEES
        WHERE  DEPARTMENT_ID = (
        SELECT DEPARTMENT_ID
        FROM   DEPARTMENTS
        WHERE  UPPER(DEPARTMENT_NAME) = 'SALES'
)
)
ORDER BY SALARY DESC
;

-----------------------------------------------------------
SELECT*
FROM EMPLOYEES A
WHERE (A.JOB_ID, A.SALARY) IN(
      SELECT JOB_ID, MIN(SALARY) 그룹별 급여
      FROM EMPLOYEES
      GROUP BY JOB_ID
)
ORDER BY A.SALARY DESC
;

-- 상관 서브 쿼리 CORELATIVE SUBQUERY
-- JOB_HISTORY 에 있는 부서번호와 DEPARTMENTS 에 있는 부서번호가 같은 부서를 찾아서
-- DEPARTMENTS 에 있는 부서번호와 부서명을 출력
    SELECT a.department_id, a.department_name
    FROM departments a
    WHERE EXISTS (SELECT 1
                  FROM job_history b
                  WHERE a.department_id = b.department_id );

-- SHIPPING 부서의 직원명단
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID = (
SELECT DEPARTMENT_ID
FROM   DEPARTMENTS
WHERE  UPPER(DEPARTMENT_NAME) = 'SHIPPING'
)
;

-----------------------------------------------------------
JOIN
-----------------------------------------------------------

---------ORACLE OLD 문법---------

-- 1. 카티션 프로젝트 : CROSS JOIN - 조건이 없는
SELECT FIRST_NAME||''||LAST_NAME,
       DEPARTMENT_NAME 
FROM   EMPLOYEES,DEPARTMENTS
;

-- 106개(부서번호 NULL-3)
-- 2.내부 조인 : INNER JOIN - 양쪽 다 존재한 DATA(NULL 제외)
SELECT FIRST_NAME||''||LAST_NAME,
       DEPARTMENT_NAME 
FROM   EMPLOYEES,DEPARTMENTS
WHERE  EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
;

SELECT FIRST_NAME||''||LAST_NAME,
       DEPARTMENT_NAME 
FROM   EMPLOYEES E, DEPARTMENTS D
WHERE  E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 3. LEFT OUTER JOIN - 기준을 정해서 
-- 모든 직원을 출력 : 109줄
-- 직원의 부서번호가 NULL 이라도 출력해야됨
-- (+) : 기준(직원)이 되는 조건의 반대방향에 붙인다
SELECT E.FIRST_NAME||''|| E.LAST_NAME 이름,
       D.DEPARTMENT_NAME 부서명 
FROM   EMPLOYEES E, DEPARTMENTS D
WHERE  E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
;

-- 4. RIGHT OUTER JOIN - 기준을 정해서 
SELECT E.FIRST_NAME||''|| E.LAST_NAME 이름,
       D.DEPARTMENT_NAME 부서명 
FROM   EMPLOYEES E, DEPARTMENTS D
WHERE  D.DEPARTMENT_ID(+) = E.DEPARTMENT_ID
;

-- 모든부서 출력
-- 직원정보가 없더라도 출력 : 122 = (109-3)+(27-11)
SELECT E.FIRST_NAME||''|| E.LAST_NAME 이름,
       D.DEPARTMENT_NAME 부서명 
FROM   EMPLOYEES E, DEPARTMENTS D
WHERE  D.DEPARTMENT_ID(+) = E.DEPARTMENT_ID
;

-- 5. FULL OUTER JOIN : OLD 문법에 존재하지 않는 명령
-- 모든 직원과 모든 부서를 출력

--------------------------------------------------------
-- 표준 SQL 문법
1. CROSS JOIN
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E CROSS JOIN DEPARTMENTS D
;


2. (INNER) JOIN -- 106
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM   EMPLOYEES E INNER JOIN DEPARTMENTS D
ON     E.DEPARTMENT_ID = D.DEPARTMENT_ID
;


3. OUTER JOIN -- 109
   1) LEFT OUTER JOIN
   SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
   FROM   EMPLOYEES E LEFT JOIN DEPARTMENTS D
   ON     E.DEPARTMENT_ID = D.DEPARTMENT_ID
;
   
   2) RIGHT OUTER JOIN -- 122
   
   SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
   FROM   EMPLOYEES E RIGHT JOIN DEPARTMENTS D
   ON     E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

   3) FULL OUTER JOIN -- 125=109+27-16
   SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
   FROM   EMPLOYEES E FULL JOIN DEPARTMENTS D
   ON     E.DEPARTMENT_ID = D.DEPARTMENT_ID
;
   
   
 -- 직원 이름, 담당업부(JOB_TITLE) : 109
 SELECT   FIRST_NAME, LAST_NAME, JOB_TITLE
 FROM     EMPLOYEES E, JOBS J
 WHERE    E.JOB_ID = J.JOB_ID
 ORDER BY FIRST_NAME, LAST_NAME
 ;
 
 SELECT   FIRST_NAME, LAST_NAME, JOB_TITLE
 FROM     EMPLOYEES E JOIN JOBS J 
 ON       E.JOB_ID = J.JOB_ID
 ORDER BY FIRST_NAME, LAST_NAME
 ;
 
 -- 부서명, 부서위치(CITY, STREET_ADDRESS)
 SELECT D.DEPARTMENT_NAME,
        CITY,
        STREET_ADDRESS
 FROM   DEPARTMENTS D JOIN LOCATIONS L
 ON     D.LOCATION_ID = L.LOCATION_ID
 ORDER BY DEPARTMENT_NAME 
 ;
 
 SELECT  D.DEPARTMENT_NAME 부서명,
          E.FIRST_NAME||''|| E.LAST_NAME 이름,
          L.CITY ||''|| L.STREET_ADDRESS
 FROM     EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
 WHERE    E.DEPARTMENT_ID = D.DEPARTMENT_ID
 AND      D.LOCATION_ID = L.LOCATION_ID
 ORDER BY 이름
 ;
 
  --INNER JOIN
 SELECT D.DEPARTMENT_NAME 부서명,
          E.FIRST_NAME||''|| E.LAST_NAME 이름,
          L.CITY ||''|| L.STREET_ADDRESS
 FROM     EMPLOYEES E 
          JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
          JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
 ORDER BY 이름
 ;
 
 --LEFT OUTER JOIN / 109
 SELECT   D.DEPARTMENT_NAME 부서명,
          E.FIRST_NAME ||''|| E.LAST_NAME 이름,
          L.CITY ||''|| L.STREET_ADDRESS 부서위치
 FROM     EMPLOYEES E 
          LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
          LEFT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
 ORDER BY 이름
 ;
 
 -- 직원명, 부서명, 국가, 부서위치(CITY, STREET_ADDRESS)
  SELECT E.FIRST_NAME||''||E.LAST_NAME,
         D.DEPARTMENT_NAME,
         C.COUNTRY_NAME,
         L.CITY ||''|| L.STREET_ADDRESS
  FROM   EMPLOYEES E
  JOIN   DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  JOIN   LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
  JOIN   COUNTRIES C ON L.COUNTRY_ID = C. COUNTRY_ID
  ORDER BY COUNTRY_NAME -- 106
  ;
  
  SELECT E.FIRST_NAME||''||E.LAST_NAME,
         D.DEPARTMENT_NAME,
         C.COUNTRY_NAME,
         L.CITY ||''|| L.STREET_ADDRESS
  FROM   EMPLOYEES E
  LEFT JOIN   DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  LEFT JOIN   LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
  LEFT JOIN   COUNTRIES C ON L.COUNTRY_ID = C. COUNTRY_ID
  ORDER BY COUNTRY_NAME -- 109
  ;
  
  SELECT E.FIRST_NAME||''||E.LAST_NAME,
         D.DEPARTMENT_NAME,
         C.COUNTRY_NAME,
         L.CITY ||''|| L.STREET_ADDRESS
  FROM   EMPLOYEES E
  FULL JOIN   DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  FULL JOIN   LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
  FULL JOIN   COUNTRIES C ON L.COUNTRY_ID = C. COUNTRY_ID
  ORDER BY COUNTRY_NAME -- 152
  ;
  
 -- 부서명, 국가 : 모든부서 : 27줄 이상
 SELECT D.DEPARTMENT_ID,
        C.COUNTRY_NAME
 FROM DEPARTMENTS D
      JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
      JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
      ORDER BY COUNTRY_NAME
;
 
 -- 직원명 , 부서위치 단 IT 부서만
 SELECT E.FIRST_NAME ||''|| E.LAST_NAME,
        L.STATE_PROVINCE ||','|| L.CITY ||','|| L.STREET_ADDRESS
 FROM   EMPLOYEES E
 JOIN   DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 JOIN   LOCATIONS L  ON D.LOCATION_ID = L.LOCATION_ID
 WHERE  D.DEPARTMENT_NAME = 'IT'
 ORDER  BY E.FIRST_NAME||''||E.LAST_NAME
 ;

-- 부서명별 월급평균
SELECT   DEPARTMENT_ID,
         ROUND(AVG(SALARY),2)
FROM     EMPLOYEES E
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID
;

-- 모든 부서 출력
-- 월급 평균이 NULL = '직원없음'
SELECT   D.DEPARTMENT_NAME, -- 27개 OUTER JOIN
         -- NVL(ROUND(AVG(E.SALARY),2), '직원없음') <- 에러
         -- NVL(ROUND(AVG(E.SALARY),2), 0) <- 정상
         DECODE(AVG(E.SALARY), NULL, '직원없음', ROUND(AVG(E.SALARY),2))
FROM     EMPLOYEES E  RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY D.DEPARTMENT_NAME
;

-- 직원의 근무연수
-- MONTH_BETWEEN(날짜1,2) : 날짜1-날짜2 : 월단위로
-- ADD_MONTH(날짜, n) : 날짜+n개월 OR 날짜-n개월
SELECT  FIRST_NAME||''||LAST_NAME                      이름,
        TO_CHAR(HIRE_DATE,'YYYY-MM-DD')                입사일,
        TO_CHAR(TRUNC(HIRE_DATE,'MONTH'),'YYYY-MM-DD') 입사월의첫번째날,
        TO_CHAR(LAST_DAY(HIRE_DATE),'YYYY-MM-DD')      입사월의마지막날,
        TRUNC(SYSDATE - HIRE_DATE)                     근무일수,
        TRUNC((SYSDATE - HIRE_DATE) / 365.2422)        근무연수,
        TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12) 근무연수
FROM    EMPLOYEES
;

-- 60번 부서 최소월급과 같은 월급자의 명단
SELECT  DEPARTMENT_ID,
        MIN(SALARY)
FROM    EMPLOYEES
WHERE   DEPARTMENT_ID = 60
GROUP BY DEPARTMENT_ID
;

SELECT  SALARY,
        FIRST_NAME,
        LAST_NAME        
FROM    EMPLOYEES
WHERE   SLARAY = 2100
;

SELECT  SALARY,
        FIRST_NAME,
        LAST_NAME        
FROM    EMPLOYEES
WHERE   SALARY = (
        SELECT MIN(SALARY)
        FROM    EMPLOYEES
)
;

-- 부서명, 부서장의 이름
-- INNER JOIN : 양쪽 다 존재하는 데이터만 출력
SELECT DEPARTMENT_NAME,
       E.FIRST_NAME||''||E.LAST_NAME
FROM   DEPARTMENTS D
JOIN   EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
;

-- 모든 부서에 대해 출력
SELECT DEPARTMENT_NAME,
       E.FIRST_NAME||''||E.LAST_NAME
FROM   DEPARTMENTS D LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
;

----------------------------------------
 결합연산자 - 줄 단위 결합
 조건 -- 두 테이블의 칸수와 타입이 동일해야 한다
 1)UNION     중복제거
 2)UNION ALL 중복 포함
 3)INTERSECT 교집합 : 
 4)MINUS     차집합 : A-B

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 80;  --34
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;  --45

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 80
UNION
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 50; --79

-- 칼럼수와 칼럼들의 TYPE 이 같으면 합쳐진다 -> 주의할것 : 의미없는 결합가능
SELECT EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES
UNION
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS;

-- 직원정보, 담당 업무

-- 직원명, 담당업무, 담당업무 히스토리

-- 사번, 업무시작일, 업무 종료일, 담당업무, 부서번호






